# Generated by Django 4.0.4 on 2022-05-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='text',
            new_name='class_about',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='title',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='title',
            new_name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='text',
        ),
    ]
