# Generated by Django 4.0.4 on 2022-05-16 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_classes', '0002_rename_text_class_class_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
