# Generated by Django 4.0.4 on 2022-05-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_classes', '0004_remove_class_class_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='image',
        ),
    ]
