# Generated by Django 4.0.4 on 2022-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_classes', '0006_class_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_time',
            field=models.TimeField(),
        ),
    ]
