# Generated by Django 4.0.4 on 2022-05-16 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_classes', '0007_alter_class_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
